server:
  port: 38080
spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9401/rsa/publicKey
  cloud:
    gateway:
      routes:
        - id: usercenter
          uri: lb://usercenter
          predicates:
            - Path=/uc/**
          filters:
            - StripPrefix=1
        - id: estore
          uri: lb://estore
          predicates:
            - Path=/estore/**
          filters:
            - StripPrefix=1
security:
  oauth2:
    client:
      client-id: ${spring.application.name}
      client-secret: 123456
      user-authorization-uri: http://localhost:8888/oauth/authorize
      access-token-uri: http://localhost:8888/oauth/token
    resource:
      id: ${spring.application.name}
      user-info-uri: user-info
    authorization:
      check-token-access: http://localhost:8888/oauth/check_token
management:
  endpoints:
    web:
      exposure:
        include: "*"
oauth2:
  whitelist-urls: /user